apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-conf-pv
  labels:   
    pv: nginx-conf-pv
spec:
  capacity:
    storage: 1Gi                              
  accessModes:                                 
  - ReadWriteMany                               
  persistentVolumeReclaimPolicy: Retain          
  nfs:                   
    path: /data/k8s/nginx-conf  
    server: 192.168.16.105
---
apiVersion: v1
kind: PersistentVolumeClaim   
metadata:
  name: nginx-conf-pvc
spec:
  accessModes:              
  - ReadWriteMany
  resources:               
    requests:
      storage: 1Gi
  selector:               
    matchLabels:
      pv: nginx-conf-pv
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-pod
  template:
    metadata:
      labels:
        app: nginx-pod
    spec:
      containers:
      - name: nginx
        image: harbor.jiangxl.com/base/k8s-nginx-service:v1
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-conf
          mountPath: /data/nginx/conf/conf.d
      volumes:
      - name: nginx-conf
        persistentVolumeClaim:
          claimName: nginx-conf-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx-pod
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 80
  - name: https
    port: 443
    targetPort: 443
    nodePort: 443 
