apiVersion: v1
kind: Service
metadata:
  labels:
    app: gitlab
  name: gitlab-svc-cluster
  namespace: jenkins
spec:
  ports:
  - name: http
    port: 80 
    targetPort: 80
  selector: 
    app: gitlab
  type: ClusterIP
