apiVersion: v1
kind: Service
metadata:
  name: newbee-mall-service
  namespace: newbee-mall
  labels:
    project: newbee-mall
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: java
    - port: 9100
      targetPort: 9100
      protocol: TCP
      name: node
  selector:
    project: newbee-mall
